# Use a base image with Java 17
FROM eclipse-temurin:17-jdk

# Set working directory
WORKDIR /app

# Copy the Maven build artifact (update .jar file name)
COPY target/Information-Flow-Tracker-0.0.1-SNAPSHOT.jar app.jar

# Set environment variable for port 
ENV PORT=8080

# Expose the port
EXPOSE 8080

# Run the Spring Boot app
ENTRYPOINT ["java", "-jar", "app.jar"]
